# Generated by Django 5.1.6 on 2025-03-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamePack', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepack',
            name='image',
        ),
        migrations.AddField(
            model_name='gamepack',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamepack',
            name='price',
            field=models.FloatField(),
        ),
    ]
