# Generated by Django 5.1.6 on 2025-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamePack', '0003_remove_gamepack_image_gamepack_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepack',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='gamepack',
            name='price',
            field=models.IntegerField(),
        ),
    ]
