# Generated by Django 5.1.6 on 2025-02-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodItem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
