# Generated by Django 5.1.6 on 2025-02-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('in_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_food', to='food.food')),
                ('out_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_food', to='food.food')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
