# Generated by Django 5.1.6 on 2025-02-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.JSONField(default=list)),
                ('pets', models.JSONField(default=list)),
                ('language', models.JSONField(default=list)),
                ('coins', models.IntegerField(default=200)),
                ('active_trades', models.JSONField(default=list)),
                ('lives_counter', models.IntegerField(default=3)),
                ('actual_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
        ),
    ]
