# Generated by Django 5.1.6 on 2025-02-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question", "0002_alter_question_correct_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnarie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("level", models.IntegerField()),
                ("sublevel", models.IntegerField()),
                ("questions", models.ManyToManyField(to="question.question")),
            ],
        ),
    ]
