# Generated by Django 5.1.6 on 2025-02-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_alter_question_correct_answer"),
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Questionnarie",
            new_name="Questionnaire",
        ),
    ]
