# Generated by Django 5.1.6 on 2025-02-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0002_remove_language_questionnaires"),
        ("questionnaire", "0002_rename_questionnarie_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="language.language",
            ),
            preserve_default=False,
        ),
    ]
