# Generated by Django 5.1.6 on 2025-02-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaire_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='sublevel',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
