# Generated by Django 5.1.6 on 2025-03-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_remove_questionnaire_sublevel_questionnaire_unlocked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="unlocked",
        ),
    ]
