# Generated by Django 5.1.6 on 2025-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hat", "Hat"),
                            ("tshirt", "T-Shirt"),
                            ("shoes", "Shoes"),
                            ("accesories", "Accessories"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "style",
                    models.ImageField(blank=True, null=True, upload_to="clothes/"),
                ),
            ],
        ),
    ]
