# Generated by Django 5.1.6 on 2025-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_clothes_style_clothes_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('hat', 'Hat'), ('eyes', 'Eyes'), ('shoes', 'Shoes'), ('accesories', 'Accessories')], max_length=20),
        ),
    ]
