# Generated by Django 5.1.6 on 2025-02-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="user",
        ),
        migrations.AddField(
            model_name="trade",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activeTrades",
                to="player.player",
            ),
        ),
    ]
