# Generated by Django 5.1.6 on 2025-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0002_rename_questionnarie_questionnaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("de", "German"),
                            ("ar", "Arabic"),
                            ("ja", "Japanese"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "questionnaires",
                    models.ManyToManyField(
                        related_name="languages", to="questionnaire.questionnaire"
                    ),
                ),
            ],
        ),
    ]
