# Generated by Django 5.1.6 on 2025-02-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="questionnaires",
        ),
    ]
