# Generated by Django 5.1.6 on 2025-02-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='actualLanguage',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('ar', 'Arabic'), ('ja', 'Japanese')], max_length=20, null=True),
        ),
    ]
