# Generated by Django 5.1.6 on 2025-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playerProgress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprogress",
            name="unloked",
            field=models.BooleanField(default=False),
        ),
    ]
