# Generated by Django 5.1.6 on 2025-03-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playerProgress", "0002_playerprogress_unloked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerprogress",
            old_name="unloked",
            new_name="unlocked",
        ),
    ]
