# Generated by Django 5.1.6 on 2025-02-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="hunger",
            field=models.IntegerField(default=100),
        ),
    ]
