# Generated by Django 5.1.6 on 2025-02-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_alter_pet_hunger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("ar", "Arabic"),
                    ("ja", "Japanese"),
                ],
                max_length=20,
            ),
        ),
    ]
