# Generated by Django 5.1.6 on 2025-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_clothes_style_clothes_image_path'),
        ('pet', '0004_pet_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='accesories',
            field=models.ManyToManyField(blank=True, null=True, related_name='pets', to='clothes.clothes'),
        ),
    ]
