# Generated by Django 5.1.6 on 2025-02-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0002_clothes_type'),
        ('coins_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lives', 'Lives'), ('coins', 'Coins'), ('clothes', 'Clothes')], default='coins', max_length=50)),
                ('quantity', models.IntegerField()),
                ('clothes_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
                ('coins_shop_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins_shop.coinsshop')),
            ],
        ),
    ]
