# Generated by Django 5.1.6 on 2025-02-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodList", "0002_remove_foodlist_user"),
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlist",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_lists",
                to="player.player",
            ),
        ),
    ]
