# Generated by Django 5.1.6 on 2025-02-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('answers', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
