# Generated by Django 5.1.6 on 2025-02-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="realPack/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lastOportunity", "Last Oportunity"),
                            ("new", "New"),
                            ("popular", "Popular"),
                        ]
                    ),
                ),
            ],
        ),
    ]
