# Generated by Django 5.1.6 on 2025-02-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("realPack", "0001_initial"),
        ("shopItem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="realpack",
            name="items",
            field=models.ManyToManyField(
                related_name="real_packs", to="shopItem.shopitem"
            ),
        ),
    ]
