# Generated by Django 5.1.6 on 2025-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realPack', '0003_remove_realpack_image_realpack_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realpack',
            name='category',
        ),
        migrations.AddField(
            model_name='realpack',
            name='rarity',
            field=models.CharField(choices=[('legendary', 'Legendary'), ('epic', 'Epic'), ('rare', 'Rare'), ('uncommon', 'Uncommon'), ('common', 'Common')], default='common'),
        ),
    ]
