# Generated by Django 5.1.6 on 2025-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.IntegerField(),
        ),
    ]
