# Generated by Django 5.1.6 on 2025-02-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foodList", "0002_remove_foodlist_user"),
        ("wardrobe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins", models.IntegerField(default=0)),
                ("livesCounter", models.IntegerField(default=0)),
                (
                    "clothes_inventory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothes_inventory",
                        to="wardrobe.wardrobe",
                    ),
                ),
                (
                    "food_inventory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_inventory",
                        to="foodList.foodlist",
                    ),
                ),
            ],
        ),
    ]
