# Generated by Django 5.1.6 on 2025-02-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='coins',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='livesCounter',
            field=models.IntegerField(default=3),
        ),
    ]
