# Generated by Django 5.1.6 on 2025-02-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realMoneyPacks', models.JSONField(default=list)),
                ('clothesPack', models.JSONField(default=list)),
            ],
        ),
    ]
