# Generated by Django 5.1.6 on 2025-02-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_item', '0001_initial'),
        ('food_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_list_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_list.foodlist'),
        ),
    ]
