# Generated by Django 5.1.6 on 2025-02-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ballingouser",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="ballingouser",
            name="telefono",
        ),
    ]
