# Generated by Django 5.1.6 on 2025-03-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_ballingouser_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballingouser',
            name='recovery_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
