# Generated by Django 5.1.6 on 2025-03-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopItem', '0002_shopitem_coins_given_shopitem_lives_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='coins_given',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='lives_given',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
