# Generated by Django 5.1.6 on 2025-02-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_food_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="language",
            field=models.CharField(max_length=2),
        ),
    ]
