# Generated by Django 5.1.6 on 2025-02-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('hat', 'Hat'), ('tshirt', 'T-Shirt'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], default='tshirt', max_length=50),
        ),
    ]
